border=no
osd-bar=no
hwdec=auto

[waves]
framedrop=vo
video-sync=audio
lavfi-complex=[aid1]asplit[ao][a1];[a1]showwaves=s=480x270:rate=30:mode=p2p:scale=sqrt:colors=000000|FFFFFF:draw=full,format=rgb24[vo]
