osd-bar=no
border=no
video-sync=display-resample
force-window=yes

[audio]
profile-cond=not vid
audio-display=no
lavfi-complex=[aid1]asplit[ao][a1];[a1]showwaves=mode=p2p:colors=000000|FFFFFF:draw=full,format=rgb24[vo]
