# -----------------------------------------------------
# Window rules
# -----------------------------------------------------
windowrule = float on, match:class ^(pavucontrol)$


windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = size 40% 65%, match:class ^(xdg-desktop-portal-gtk)$

windowrule = float on, match:class ^(net.ankiweb.Anki)$ title:^(Add)$
windowrule = size 40% 65%, match:class ^(net.ankiweb.Anki)$ title:^(Add)$

windowrule = float on, match:class ^(qalculate-gtk)$ 
windowrule = size 40% 65%, match:class ^(qalculate-gtk)$

windowrule = float on, match:class ^(qalculate-qt)$ 
windowrule = size 40% 65%, match:class ^(qalculate-qt)$

# Smart borders and rounding
windowrule = border_size 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = border_size 0, match:float 0, match:workspace f[1]s[false]

windowrule = rounding 5, match:float 1, match:workspace w[tv1]s[false]
